### ISSUE TITLE
field binary generator

### ISSUE THREAD

**Issue by ZallFauz** [haritsahm/monte-carlo-localization#1]
Is there any source code to generate the field binary?

**Comment by haritsahm** [comment]
@ZallFauz sorry for the late response, I didn't recieved any notification. As far as I remember, I generated the binary files using opencv. Draw black canvas similar to the size of the field, draw field lines according to the fields, and finally generate the binary masks using opencv distance transform. Detailed explanation should be available in the references and I'll update the codes if I found it
