### ISSUE TITLE
Error build without any QT. 

### ISSUE THREAD

**Issue by HatfanSahrul1** [haritsahm/monte-carlo-localization#2]
so I tried to build this code without using QT, just mcl.h mcl.cpp mcl_properties.h. I have adjusted the code so that it doesn't error without QT, but I encountered an error that said "undefined reference to `MCL::publishPoints(std::vector<cv::Point_<float>, std::allocator<cv::Point_<float > > >)' " and some similar error precisely on the signal on line 61 mcl.h. Can I get a solution? or is there any particular way to build without QT? I'm kinda new to this
Thank you:)

**Comment by haritsahm** [comment]
I apologize for the very late response, I didn't get any notification about this issue. This app is intended to run with Qt installed and usually preinstalled in Ubuntu. What environment are you using to compile the application? 
- Windows/Linux OS Version: ? 
- Qt Version: ?
- OpenCV Version: ?
- GCC/G++: ?
- Cmake outputs (copy the outputs)
```
cmake . 
-----
-----
```
- make outputs (copy the outputs)
```
make
-----
-----
```

**Comment by HatfanSahrul1** [comment]
hi. i'm sorry for very late to response back. and thank you for responding
so, i m using :

- os : ubuntu 20.04
- qt version : 
    > $ qmake --version
    > QMake version 3.1
    > Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu

- OpenCV : 4.8.1
- g++ : 
    >  g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

I've tried various ways to build this project until finally it build successfully without any errors, but I don't know if I'm doing it correctly. 
Please allow me to attach my modified codes, and I hope you can review it to verify whether I have done it correctly.
[mcl.zip](https://github.com/user-attachments/files/17719209/mcl.zip)
(i'm sorry i had to .zip it)

If I am doing it correctly, could you tell me which function I need to continuously update in the main function to keep this program running, even without visualization? I’m also very curious about how the distance_matrix works in calculating distances. Was this distance_matrix obtained from the .bin file? Can I create my own .bin file? to be honest i have no idea how it works. I would greatly appreciate your answer. Thank you very much:)

**Comment by haritsahm** [comment]
It is better to rewrite everything because the current code depends on qt to run. As long as you understand how the mcl works, then you should be able to reuse the codes in mcl.  

The distance matrix can be created using opencv. Create a blank (zeros) 2d grid with the shape of the field, draw all the lines and circles based on the field properties, then use L2 distance function to compute the cost matrix. You can also invert the final cost matrix depending on how you plan to use it.

**Comment by HatfanSahrul1** [comment]
Thank you very much.  I no longer encounter any errors. I will try to rewrite it and learn more about the distance matrix one
